### ISSUE TITLE
Adding docker as installation method

### ISSUE THREAD

**Issue by tuahk** [rayrod2030/chef-prometheus#1]
Hi

Using Docker might be something that this cookbook should provide?
I have all ready experimented with it in my cookbook so there is something to build upon.

**Comment by rayrod2030** [comment]
The installation types that I am thinking would be most common are source, binary and package whenever native prometheus packages do emerge.  Is it actually common for chef cookbook to install applications via docker?  Do you know of any other cookbooks that offer this functionality?

**Comment by rayrod2030** [comment]
Yup absolutely that makes a lot of sense.  That bit of code will likely be reused across all the init templates.
