### ISSUE TITLE
Writing unit tests for source.rb

### ISSUE THREAD

**Issue by tuahk** [rayrod2030/chef-prometheus#2]
Hi,

Maybe I could write unit test with ChefSpec?

**Comment by rayrod2030** [comment]
Yeah that would be useful.  I've added only a few very high level serverspec tests but chefspec tests would be great for faster feedback.

**Comment by tuahk** [comment]
Great! I start working on this an make PR when done

**Comment by rayrod2030** [comment]
Work to start improving unit testing has been started with this PR: https://github.com/rayrod2030/chef-prometheus/pull/8.
