### ISSUE TITLE
Updating README

### ISSUE THREAD

**Issue by tuahk** [rayrod2030/chef-prometheus#31]
This cookbooks README is failing to inform about new functionality that has been added. We probably should update it a bit.

**Comment by rayrod2030** [comment]
I'm about to do a release and will update the README as part of the release.  Thanks for the heads up!

**Comment by rayrod2030** [comment]
Readme updated: https://github.com/rayrod2030/chef-prometheus/commit/305db97ef1f741c9f8df736d39897a1261ad5dae

**Comment by tuahk** [comment]
Alright, that's great!
