### ISSUE TITLE
Add additional init styles

### ISSUE THREAD

**Issue by rayrod2030** [rayrod2030/chef-prometheus#4]
In addition to supporting runit this cookbook should support other init styles such as:

- [x] SysV Init.d - started in https://github.com/rayrod2030/chef-prometheus/pull/16
- [ ] Upstart
- [x] Systemd - started in https://github.com/rayrod2030/chef-prometheus/pull/25
- [x] Bluepill - started in https://github.com/rayrod2030/chef-prometheus/pull/14

**Comment by tuahk** [comment]
Good idea.
There is a cookbook for Bluepill and a service for Upstart so I can start by adding support for those two.

**Comment by rayrod2030** [comment]
Yeah I'm going to try to knock out at least SysV init and upstart using the nginx cookbook as inspiration.

**Comment by tuahk** [comment]
It seems like the same string of flags is needed in all of the different init-erb files. So how would you feel if I moved that code generating config-string in sv-prometheus-run.erb to libraries/help_functions.rb? Or do you happen to have some better idea how not to write the same code in multiple erb files?

**Comment by tuahk** [comment]
Seems like we both said that we are going to add support for upstart. To avoid duplicate work we probably should decided who is doing this. I could start working on this as soon as I have time but if this is something you want to implement then I can move on to per-compailed binary installation?

**Comment by rayrod2030** [comment]
Yeah I was planning on doing the upstart init today or tomorrow.
